// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyitozjcniebutdqkbmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5aXRvempjbmllYnV0ZHFrYm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDY5ODEsImV4cCI6MjA1ODAyMjk4MX0.lhwjN0WuYShQe_FYPEvOC--PjUm9DVUB3NbRAEtT53g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);